In [1]:
import selenium
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
import time
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

# 1. Write a python program which searches all the product under a particular product from www.amazon.in. The product to be searched will be taken as input from user. For e.g. If user input is ‘guitar’. Then search for guitars.

In [2]:
# Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [3]:
url = 'http://www.amazon.in/' # giving the url to the variable

In [4]:
driver.get(url) # Calling the url in the webdriver

In [5]:
s = input("Enter what is to be searched:\t") #Taking input from the user to what is to be searched

Enter what is to be searched:	phone

In [6]:
search = driver.find_element_by_id("twotabsearchtextbox") #selecting the search box

In [7]:
search.send_keys(s) #giving the input to the webdriver

In [8]:
btn = driver.find_element_by_id("nav-search-submit-button") #Locating the search button

In [9]:
btn.click() #Clicking the search button

In [10]:
link = [] #defining an empty array

In [11]:
# Forming a loop to collect all the product links
for j in range(0,3):
    tag = driver.find_elements_by_xpath('//a[@class="a-link-normal s-link-style a-text-normal"]')
    for i in tag:
        link.append(i.get_attribute('href'))
    btn = driver.find_element_by_xpath('//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
    bt = btn.get_attribute('href')
    driver.get(bt)

In [12]:
len(link)

66

# 2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product has less than 3 pages in search results then scrape all the products available under that product name. Details to be scraped are: "Brand Name", "Name of the Product", "Price", "Return/Exchange", "Expected Delivery", "Availability" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“.

In [14]:
# Defining empty arrays for the data to be scraped
brand = []
name = []
prc = []
ret = []
deli = []
avail = []
purl = []

In [15]:
# Forming a loop to scrape all the data required
for url in link:
    driver.get(url) #Calling each url one-by-one
    
    #Scraping brand name
    try:
        tag1 = driver.find_element_by_id('productTitle')
        brand.append(tag1.text.split()[0])
    except:
        brand.append("-")
    
    #Scraping Product Name
    try:
        tag2 = driver.find_element_by_id('productTitle')
        name.append(tag2.text)
    except:
        name.append("-")
        
    #Scraping Price
    try:
        tag3 = driver.find_element_by_xpath('//span[@class="a-price a-text-price a-size-medium apexPriceToPay"]/span[2]')
        prc.append(tag3.text)
    except:
        prc.append("-")
        
    #Scraping Return/Exchange
    try:
        tag4 = driver.find_element_by_id('RETURNS_POLICY')
        ret.append(tag4.text)
    except:
        ret.append("-")
        
    #Scraping Delivery 
    try:
        tag5 = driver.find_element_by_xpath('//div[@id="ddmDeliveryMessage"]/b[1]')
        deli.append(tag5.text)
    except:
        deli.append("-")
        
    #Scraping Availability
    try:
        tag6 = driver.find_element_by_xpath('//div[@id="availability"]/span[1]')
        avail.append(tag6.text)
    except:
        avail.append("-")
        
    #Scraping Product URL
    purl.append(url)

In [16]:
#Creating a DataFrame of the scraped data
df = pd.DataFrame({"Brand Name":brand, 
                   "Name of the Product":name, 
                   "Price":prc,
                   "Return/Exchange":ret,
                   "Expected Delivery":deli,
                   "Availability":avail,
                   "Product URL":purl})

In [18]:
df

,Brand Name,Name of the Product,Price,Return/Exchange,Expected Delivery,Availability,Product URL
0,Samsung,Samsung Galaxy M21 2021 Edition (Charcoal Blac...,"₹11,999.00",7 Days Replacement,"Tuesday, Jan 25",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
1,Samsung,"Samsung Galaxy M52 5G (ICY Blue, 6GB RAM, 128G...","₹24,999.00",7 Days Replacement,"Tuesday, Jan 25",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
2,Redmi,"Redmi 9A (Nature Green, 2GB RAM, 32GB Storage)...","₹7,499.00",7 Days Replacement,Jan 31 - Feb 3,,https://www.amazon.in/Redmi-9A-2GB-32GB-Storag...
3,OPPO,"OPPO A31 (Fantasy White, 6GB RAM, 128GB Storag...","₹12,990.00",7 Days Replacement,"Tuesday, Jan 25",In stock.,https://www.amazon.in/Oppo-Fantasy-Storage-Add...
4,Nokia,Nokia 105 Single SIM (Black),"₹1,249.00",7 Days Replacement,"Tuesday, Jan 25",In stock.,https://www.amazon.in/Nokia-105-2019-Single-Bl...
...,...,...,...,...,...,...,...
61,I,"I KALL K3310 Dual Sim Keypad Mobile (1.8 Inch,...",₹729.00,7 Days Replacement,"Friday, Jan 28",In stock.,https://www.amazon.in/IKALL-K3310-Dual-Light-B...
62,OPPO,"OPPO A74 5G (Fantastic Purple,6GB RAM,128GB St...","₹16,990.00",7 Days Replacement,"Tuesday, Jan 25",In stock.,https://www.amazon.in/OPPO-Fantastic-Purple-12...
63,I,"I KALL Z1 4G Smartphone (2GB, 16GB, Android 8....","₹5,499.00",7 Days Replacement,"Saturday, Jan 29",In stock.,https://www.amazon.in/KALL-Smartphone-16GB-And...
64,I,"I KALL Z7 Smartphone (6.26"", 4GB, 32GB) (Grey)","₹6,499.00",7 Days Replacement,"Friday, Jan 28",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...
65,Lava,Lava A1 Josh 21-Dual Sim |Call Blink Notficati...,₹979.00,7 Days Replacement,"Tuesday, Jan 25",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...

# 3. Write a python program to access the search bar and search button on images.google.com and scrape 10 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’, ‘Guitar’, ‘Cakes’.

In [39]:
# Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [40]:
url = 'https://images.google.com/' # Giving the website to the variable

In [41]:
# Creating an array for all the keywords that is to be searched on the website
key = ['fruits', 'cars', 'Machine Learning', 'Guitar', 'Cakes']

In [45]:
# Creating a DataFrame for the scraped data
df = pd.DataFrame()

In [46]:
# We create a loop to scrape all the data required
for i in key:
    driver.get(url)   # Calling the website on the webdriver
    src = driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')  #Locating the search column
    src.send_keys(i)  # Sending data that is to be searched
    btn = driver.find_element_by_xpath('//button[@class="Tg7LZd"]')     #Locating the search button
    btn.click()       #Clicking on Search
    tag = driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')  #Locating all the data that contains the image link
    img = []  # Creating an empty array to scrape the data
    for j in tag[:10]:
        img.append(j.get_attribute('src')) # Scraping the top 10 data
    df[i] = img  #Adding the data to the dataframe

In [47]:
df

,fruits,cars,Machine Learning,Guitar,Cakes
0,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
1,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
2,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
3,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
4,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
5,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
6,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
7,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
8,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
9,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."

# 4. Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [4]:
# Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [5]:
url = 'https://www.flipkart.com' # Giving the website to the variable

In [6]:
# Calling the website on the webdriver
driver.get(url)

In [7]:
#Locating the search column
src = driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input')
#Sending data that is to be searched
src.send_keys("pixel 4A")

In [8]:
#Locating the search button
btn = driver.find_element_by_xpath('/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/button')
#Clicking on Search
btn.click()

In [9]:
#Creating an empty array to store the link for the products
link = []

In [10]:
#Scraping the link to all the products on page 1
tag = driver.find_elements_by_xpath('//a[@class="_1fQZEK"]')
for i in tag:
    link.append(i.get_attribute('href'))

In [11]:
len(link)

24

In [12]:
# Defining empty arrays for the data to be scraped
brand = []
name = []
clr = []
ram = []
rom = []
pcm = []
scm = []
dis = []
btt = []
prc = []
purl = []

In [13]:
# Forming a loop to scrape all the data required
for url in link:
    driver.get(url) #Calling each url one-by-one
    
    #Scraping brand name
    try:
        tag1 = driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        brand.append(tag1.text.split()[0])
    except:
        brand.append("-")
    
    #Scraping Product Name
    try:
        tag2 = driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        name.append(tag2.text.split("(")[0])
    except:
        name.append("-")
        
    #Scraping Colour
    try:                                     
        tag3 = driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        clr.append(tag3.text.split("(")[1].split(",")[0])
    except:
        clr.append("-")
        
    #Scraping RAM
    try:
        tag4 = driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        ram.append(tag4.text.split("(")[-1].split(")")[0])
    except:
        ram.append("-")
    
    #Scraping ROM
    try:
        tag5 = driver.find_element_by_xpath('//span[@class="B_NuCI"]')
        rom.append(tag5.text.split("(")[1].split(",")[1].split(")")[0])
    except:
        rom.append("-")
        
    #Scraping Primary Camera
    try:
        tag6 = driver.find_element_by_xpath('//div[@class="_2418kt"]/ul/li[3]')
        pcm.append(tag6.text.split("|")[0])
    except:
        pcm.append("-")
        
    #Scraping Secondary Camera
    try:
        tag7 = driver.find_element_by_xpath('//div[@class="_2418kt"]/ul/li[3]')
        scm.append(tag7.text.split("|")[1])
    except:
        scm.append("-")
        
    #Scraping Display
    try:
        tag8 = driver.find_element_by_xpath('//div[@class="_2418kt"]/ul/li[2]')
        dis.append(tag8.text)
    except:
        dis.append("-")
        
    #Scraping Battery
    try:
        tag9 = driver.find_element_by_xpath('//div[@class="_2418kt"]/ul/li[4]')
        btt.append(tag9.text)
    except:
        btt.append("-")
        
    #Scraping Price
    try:
        tag10 = driver.find_element_by_xpath('//div[@class="_30jeq3 _16Jk6d"]')
        prc.append(tag10.text)
    except:
        prc.append("-")
        
    #Scraping Product URL
    purl.append(url)

In [14]:
#Creating a DataFrame of the scraped data
df = pd.DataFrame({"Brand Name":brand, 
                   "Smartphone Name":name,
                   "Colour":clr,
                   "RAM":ram,
                   "Storage(ROM)":rom,
                   "Primary Camera":pcm,
                   "Secondary Camera":scm,
                   "Display Size":dis,
                   "Battery Capacity":btt,
                   "Price":prc,
                   "Product URL":purl})

In [15]:
df

,Brand Name,Smartphone Name,Colour,RAM,Storage(ROM),Primary Camera,Secondary Camera,Display Size,Battery Capacity,Price,Product URL
0,Google,Google Pixel 4a,Just Black,6 GB RAM,128 GB,12.2MP Rear Camera,8MP Front Camera,14.76 cm (5.81 inch) Full HD+ Display,3140 mAh Battery,"₹28,999",https://www.flipkart.com/google-pixel-4a-just-...
1,REDMI,REDMI 10 Prime,Astral White,4 GB RAM,64 GB,50MP + 8MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) Full HD Display,6000 mAh Battery,"₹14,098",https://www.flipkart.com/redmi-10-prime-astral...
2,SAMSUNG,SAMSUNG Galaxy M52 5G,Blazing Black,6 GB RAM,128 GB,64MP + 12MP + 5MP,32MP Front Camera,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹26,999",https://www.flipkart.com/samsung-galaxy-m52-5g...
3,REDMI,REDMI 9 Power,Fiery Red,4 GB RAM,64 GB,48MP + 8MP + 2MP + 2MP,8MP Front Camera,16.59 cm (6.53 inch) Full HD+ Display,6000 mAh Battery,"₹13,990",https://www.flipkart.com/redmi-9-power-fiery-r...
4,REDMI,REDMI NOTE 10 LITE,Glacier White,4 GB RAM,128 GB,48MP Rear Camera,-,16.94 cm (6.67 inch) Display,5020 mAh Battery,"₹14,689",https://www.flipkart.com/redmi-note-10-lite-gl...
5,Redmi,Redmi 9A,Midnight Black,2 GB RAM,32 GB,13MP Rear Camera,-,16.59 cm (6.53 inch) Full HD+ Display,5000 mAh Battery,"₹7,698",https://www.flipkart.com/redmi-9a-midnight-bla...
6,Redmi,Redmi 9A,Nature Green,2 GB RAM,32 GB,13MP Rear Camera,-,16.59 cm (6.53 inch) Full HD+ Display,5000 mAh Battery,"₹7,729",https://www.flipkart.com/redmi-9a-nature-green...
7,Redmi,Redmi 9A,SeaBlue,2 GB RAM,32 GB,13MP Rear Camera,-,16.59 cm (6.53 inch) Full HD+ Display,5000 mAh Battery,"₹7,709",https://www.flipkart.com/redmi-9a-seablue-32-g...
8,Tecno,Tecno Spark Go 2021,Galaxy Blue,2 GB RAM,32 GB,13MP Rear Camera,8MP Front Camera,16.56 cm (6.52 inch) HD+ Display,5000 mAh Battery,"₹7,549",https://www.flipkart.com/tecno-spark-go-2021-g...
9,Redmi,Redmi 9,Sporty Orange,4 GB RAM,64 GB,13MP + 2MP,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹10,889",https://www.flipkart.com/redmi-9-sporty-orange...
10,REDMI,REDMI Note 10 Pro,Vintage Bronze,8 GB RAM,128 GB,64MP Rear Camera,-,16.94 cm (6.67 inch) Display,5020 mAh Battery,"₹20,340",https://www.flipkart.com/redmi-note-10-pro-vin...
11,Redmi,Redmi 9,Sky Blue,4 GB RAM,64 GB,13MP + 2MP,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹10,900",https://www.flipkart.com/redmi-9-sky-blue-64-g...
12,Redmi,Redmi 9A Sport,Metallic Blue,3 GB RAM,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,638",https://www.flipkart.com/redmi-9a-sport-metall...
13,Redmi,Redmi 9A Sport,Coral Green,3 GB RAM,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,476",https://www.flipkart.com/redmi-9a-sport-coral-...
14,Tecno,Tecno Spark 7T,Nebula Orange,4 GB RAM,128 GB,48MP Rear Camera,8MP Front Camera,16.56 cm (6.52 inch) HD+ Display,6000 mAh Battery,"₹10,773",https://www.flipkart.com/tecno-spark-7t-nebula...
15,SAMSUNG,SAMSUNG Galaxy M02,Black,3 GB RAM,32 GB,13MP + 2MP,5MP Front Camera,16.64 cm (6.55 inch) Full HD+ Display,5000 mAh Battery,"₹9,805",https://www.flipkart.com/samsung-galaxy-m02-bl...
16,Itel,Itel A25,Gradation Purple,1 GB RAM,16 GB,5MP Rear Camera,2MP Front Camera,12.7 cm (5 inch) HD Display,3020 mAh Battery,"₹4,899",https://www.flipkart.com/itel-a25-gradation-pu...
17,Redmi,Redmi 9A Sport,Coral Green,2 GB RAM,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,098",https://www.flipkart.com/redmi-9a-sport-coral-...
18,Redmi,Redmi 9A Sport,Carbon Black,3 GB RAM,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹8,410",https://www.flipkart.com/redmi-9a-sport-carbon...
19,Redmi,Redmi 9A Sport,Carbon Black,2 GB RAM,32 GB,13MP Rear Camera,5MP Front Camera,16.59 cm (6.53 inch) HD+ Display,5000 mAh Battery,"₹7,829",https://www.flipkart.com/redmi-9a-sport-carbon...
20,Tecno,Tecno Spark 7,Magnet Black,2 GB RAM,32 GB,16MP Rear Camera,8MP Front Camera,16.56 cm (6.52 inch) HD+ Display,6000 mAh Battery,"₹7,976",https://www.flipkart.com/tecno-spark-7-magnet-...
21,SAMSUNG,SAMSUNG Galaxy M52 5G,Icy Blue,6 GB RAM,128 GB,64MP + 12MP + 5MP,32MP Front Camera,17.02 cm (6.7 inch) Full HD+ Display,5000 mAh Battery,"₹25,399",https://www.flipkart.com/samsung-galaxy-m52-5g...
22,REDMI,REDMI 10 Prime,Bifrost Blue,4 GB RAM,64 GB,50MP + 8MP + 2MP + 2MP,8MP Front Camera,16.51 cm (6.5 inch) Full HD Display,6000 mAh Battery,"₹14,290",https://www.flipkart.com/redmi-10-prime-bifros...
23,Itel,Itel A25,Gradation Blue,1 GB RAM,16 GB,5MP Rear Camera,2MP Front Camera,12.7 cm (5 inch) HD Display,3020 mAh Battery,"₹4,880",https://www.flipkart.com/itel-a25-gradation-bl...

In [16]:
#Saving the data into csv file
df.to_csv(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\Web Scrapping_3 27-01\Q4_data.csv")

# 5. Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [106]:
# Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [107]:
driver.get("https://www.google.com/maps/") #Calling the website on the webdriver

In [108]:
key = input("Enter the city name:\t") #Taking imput from the user

Enter the city name:	Bangkok

In [109]:
srch = driver.find_element_by_id('searchboxinput') #Locating the search bar
srch.send_keys(key)  #Giving the city name to be searched

In [110]:
btn = driver.find_element_by_xpath('//button[@class="nhb85d-BIqFsb"]')  #Locating the search button
btn.click()  #Clicking on search
driver.implicitly_wait(10) #Waiting 10sec for the website to load

In [114]:
# Try function to locate the city element
try:
    WebDriverWait(driver, 20).until(EC.presence_of_element_located((By.XPATH,'//a[@class="gb_1d gb_1 gb_1c"]'))) 
    tag = driver.find_element_by_xpath('//a[@class="gb_1d gb_1 gb_1c"]')
    k = tag.get_attribute('href')
except: 
    print("City not found!")

In [115]:
k

'https://accounts.google.com/ServiceLogin?hl=en&passive=true&continue=https%3A%2F%2Fwww.google.com%2Fmaps%2Fplace%2FBangkok%2C%2BThailand%2F%4013.7244416%2C100.3529093%2C10z%2Fdata%3D!4m5!3m4!1s0x311d6032280d61f3%3A0x10100b25de24820!8m2!3d13.7563309!4d100.5017651&service=local&ec=GAZAcQ'

In [116]:
lon = []
lon = k.split("F%40")[1].split("%2C")[0]
print("Longitude:\t",lon)

lat = []
lat = k.split("F%40")[1].split("%2C")[1]
print("Latitude:\t",lat)

Longitude:	 13.7244416
Latitude:	 100.3529093

# 6. Write a program to scrap details of all the funding deals for first quarter (i.e Jan 21 – March 21) from trak.in.

In [117]:
# Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [118]:
driver.get("https://www.trak.in") #Calling the website on the webdriver

In [119]:
btn = driver.find_element_by_id('menu-item-51510') # Locating the funding menu option
btn.click() #Clicking on the funding menu

In [128]:
tag = driver.find_elements_by_xpath('//tbody[@class="row-hover"]') #Scraping location for all the tables present
month = [0,'March', 'February', 'January'] #Initiating a month variable

In [132]:
#Creating a for loop to extract selected data from the dataset
for i in range(1,4):
    print("Data for month ",month[i], " 2021 :\n")
    data = tag[i].text.split('\n')
    for j in data:
        print(j,"\n")

Data for month  March  2021 :

1 04/03/2021 DealShare E-commerce Online shopping platform Jaipur, Rajasthan Innoven Capital Debt Financing 250,000,000

2 31/03/2021 Uniphore Technology Conversational Service Automation (CSA) Palo Alto Sorenson Capital Partners Series D 140,000,000

3 30/03/2021 Dunzo E-commerce Hyper-local delivery app Bengaluru Krishtal Advisors Pte Ltd Series E 8,000,000

4 30/03/2021 BYJU’S Edu-tech Online tutoring Bengaluru MC Global Edtech, B Capital, Baron, others Series F 460,000,000

5 23/03/2021 SkilloVilla Edu-tech Career and job-oriented upskilling. Bengaluru Titan Capital, others Seed 300,000,000

6 25/03/2021 CityMall E-commerce Social ecommerce and online grocery platform Gurgaon Accel Partners Series A 11,000,000

7 26/03/2021 DotPe FinTech Commerce and payments platform to offline enterprise businesses. Gurgaon PayU Series A 27,500,000

Data for month  February  2021 :

1 11/02/2021 Doubtnut Edu Tech E-Learning Platform Gurgaon SIG Global, Sequoia Capital, WaterBridge Ventures and ON Mauritius Series B 2,500,000

2 22/02/2021 Zomato Hospitality Online Food Delivery Platform Gurgaon Tiger Global, Kora Venture 250,000,000

3 19/02/2021 Fingerlix Hospitality Semi-cooked food delivery app Mumbai Rhodium Trust, Accel Partners and Swiggy Series C 2,747,045.20

4 17/02/2021 Zolve FinTech Global Neobank Venture Mumbai Accel Partners and Lightspeed Venture Partners Seed 1,50,00,000

5 15/02/2021 KreditBee Finance Digital lending platform Bengaluru Azim Premji’s PremjiInvest and South Korea’s Mirae Asset Venture Series C 75,000,000

6 12/02/2021 Pepperfry E-commerce Multi-brand furniture brand Mumbai InnoVen Capital Debt Financing 4,773,958

7 12/02/2021 Grofers E-Commerce Online supermarket Gurgaon SoftBank Vision Fund (SVF) Unspecified 55,000,000

8 09/02/2021 Nothing Technology Consumer Technology Venture London GV Series A 15,000,000

9 09/02/2021 SplashLearn EdTech Game-based learning programme Gurgaon Owl Ventures Series C 18,000,000

Data for month  January  2021 :

1 15/01/2021 Digit Insurance Financial Services Insurance Services Bengaluru A91 Partners, Faering Capital, TVS Capital Funds Venture 1,80,00,000

2 28/01/2021 Bombay Shaving Company Consumer Goods Company Shave care, beard care, and skincare products New Delhi Reckitt Benckiser Venture 6,172,258.50

3 19/01/2021 DeHaat AgriTech Startup online marketplace for farm products and services Patna Prosus Ventures Series C 30,000,000

4 19/01/2021 Darwinbox SaaS HR Tech Mumbai Salesforce Ventures Seed 15,000,000

5 18/01/2021 mfine Health Tech Startup AI-powered telemedicine mobile app Bengaluru Heritas Capital Management Venture Round 16,000,000

6 18/01/2021 Udayy EdTech Online learning platform for kids in class 1-5 Gurgaon Sequoia Capital Seed Funding 15,000,000

7 11/01/2021 True Elements Food Startup Whole Food plant based Nashta Pune SIDBI Venture Capital Series 100,000,000

8 13/01/2021 Saveo B2B E-commerce Pharmacies Bengaluru Matrix Partners India, RTP Global, others Seed 4,000,000

# 7. Write a program to scrap all the available details of best gaming laptops from digit.in.

In [203]:
# Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [204]:
driver.get("https://www.digit.in") #Calling the website on the webdriver

In [205]:
#Selecting the laptops menu
btn = driver.find_element_by_xpath('/html/body/div[2]/div/div[4]/ul/li[3]')
btn.click()

In [206]:
#Selecting the best gaming laptop option
btn = driver.find_element_by_xpath('/html/body/div[7]/div/div[2]/div[2]/ul/li[10]')
btn.click()

In [214]:
#Scraping the product name
tag = driver.find_elements_by_xpath('//div[@class="TopNumbeHeading active sticky-footer"]/a')
name= []
for i in tag:
    name.append(i.text)

In [215]:
len(name)

10

In [216]:
#Scraping the product summary
tag = driver.find_elements_by_xpath('//div[@class="Section-center"]/p')
smr = []
for i in tag:
    smr.append(i.text)

In [217]:
len(smr)

10

In [218]:
#Scraping the Product Specification
tag = driver.find_elements_by_xpath('//div[@class="Spcs-details"]')
spc = []
for i in tag:
    spc.append(i.text.split("\n"))

In [219]:
len(spc)

10

In [220]:
#Creating DataFrame for the scraped data
df = pd.DataFrame({'Product Name':name,
                   'Summary':smr,
                   'Specification':spc})

In [221]:
df

,Product Name,Summary,Specification
0,ACER NITRO 5,Possibly the best value-for-money gaming lapto...,"[SPECIFICATION, OS : Windows 10, Display : 15...."
1,MSI STEALTH 15M,If you’re looking for a powerful gaming laptop...,"[SPECIFICATION, OS : Windows 10, Display : 15...."
2,ASUS ROG STRIX SCAR 15,If you want possibly the best performance poss...,"[SPECIFICATION, OS : Windows 10, Display : 15...."
3,ALIENWARE AREA 51M R2,If you want the absolute best when it comes to...,"[SPECIFICATION, OS : Windows 10 Home, Display ..."
4,ALIENWARE M15 R3,If the Area 51M is a bit too much for you then...,"[SPECIFICATION, OS : Windows 10 Home, Display ..."
5,ASUS ROG STRIX SCAR 15,When the ASUS ROG Strix Scar 15 ended up on ou...,"[SPECIFICATION, OS : Windows 10 Home, Display ..."
6,ASUS ZEPHYRUS G14,The Asus Zephyrus G14 is a first-of-its-kind g...,"[SPECIFICATION, OS : Windows 10 Home, Display ..."
7,LENOVO LEGION 5I,Lenovo's Legion 5i is also a suitable laptop f...,"[SPECIFICATION, OS : Windows 10 Pro, Display :..."
8,ASUS ROG ZEPHYRUS DUO 15,The machine is powered by an Intel Core i7-108...,"[SPECIFICATION, OS : Windows 10, Display : 15...."
9,ACER ASPIRE 7 GAMING LAPTOP,The Acer Aspire 7 gaming laptop is a very capa...,"[SPECIFICATION, OS : Windows 10 Home, Display ..."

# 8. Write a python program to scrape the details for all billionaires from www.forbes.com. Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, “Industry”.

In [260]:
#Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [261]:
driver.get("https://www.forbes.com") #Calling the website on the webdriver

In [262]:
#Locating and clicking on the drop down menu
btn = driver.find_element_by_xpath('//button[@class="icon--hamburger"]')
btn.click()

In [263]:
#Locating and clicking on the billionare option
btn = driver.find_element_by_xpath('//li[@class="header__channel header__color--centennial-silver header__hoverable"]')
btn.click()

In [264]:
#Locating and clicking on the World Billionare option
btn = driver.find_element_by_xpath('/html/body/div[1]/header/nav/div[3]/ul/li[1]/div[2]/ul/li[2]/a')
btn.click()

In [265]:
#Creating Empty Arrays for the data to be scraped
rank = []
name = []
nw = []
age = []
cit = []
src = []
ind = []
i = 0
p = ['0']
k = 2674

In [266]:
#Creating a loop to scrape the required data
while i<k:
    
    tag1 = driver.find_elements_by_xpath('//div[@class="rank"]')  #Locating Rank
    for j in tag1:
        rank.append(j.text.split('.')[0])
        p = rank[-1]
    
    tag2 = driver.find_elements_by_xpath('//div[@class="personName"]')  #Locating Name
    for j in tag2:
        name.append(j.text)
    
    tag3 = driver.find_elements_by_xpath('//div[@class="netWorth"]')  #Locating Net Worth
    for j in tag3:
        nw.append(j.text)
    
    tag4 = driver.find_elements_by_xpath('//div[@class="age"]')  #Locating Age
    for j in tag4:
        age.append(j.text)
    
    tag5 = driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]')  #Locating Citizenship
    for j in tag5:
        cit.append(j.text)
    
    tag6 = driver.find_elements_by_xpath('//div[@class="source-column"]')  #Locating Source
    for j in tag6:
        src.append(j.text)
    
    tag7 = driver.find_elements_by_xpath('//div[@class="category"]')  #Locating Industry
    for j in tag7:
        ind.append(j.text)
    
    i = int(p)
    
    try:
        btn = driver.find_element_by_xpath('//div[@class="next-page"]')
        btn.click()
    except ElementClickInterceptedException as e:
        pass

In [267]:
#Creating a DataFrame for the scraped data
df = pd.DataFrame({'Rank':rank,
                   'Name':name,
                   'Net Worth':nw,
                   'Age':age,
                   'Citizenship':cit,
                   'Source':src,
                   'Industry':ind})

In [268]:
df

,Rank,Name,Net Worth,Age,Citizenship,Source,Industry
0,1,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
2750,2674,Daniel Yong Zhang,$1 B,49,China,e-commerce,Technology
2751,2674,Zhang Yuqiang,$1 B,65,China,Fiberglass,Manufacturing
2752,2674,Zhao Meiguang,$1 B,58,China,gold mining,Metals & Mining
2753,2674,Zhong Naixiong,$1 B,58,China,conglomerate,Diversified
2754,2674,Zhou Wei family,$1 B,54,China,Software,Technology

# 9. Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [325]:
#Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [326]:
driver.get("https://www.youtube.com") #Calling the website on the webdriver

In [327]:
# Clicking on the first suggested video
btn = driver.find_element_by_xpath('/html/body/ytd-app/div/ytd-page-manager/ytd-browse/ytd-two-column-browse-results-renderer/div[1]/ytd-rich-grid-renderer/div[6]/ytd-rich-grid-row[1]/div/ytd-rich-item-renderer[1]/div/ytd-rich-grid-media/div[1]/div[2]/div[1]/h3/a')
btn.click()

In [328]:
#Creating empty list to store the scraped data
cmt = []
up = []
tm = []

In [329]:
j=k=l=0
while j<500:
    #Locating and scraping comments
    tag = driver.find_elements_by_xpath('//div[@class="style-scope ytd-expander"]/yt-formatted-string[2]')
    for i in tag:
        if j<500:
            cmt.append(i.text)
            j+=1
    
    #Locating and scraping upvotes
    tag = driver.find_elements_by_id('vote-count-middle')
    for i in tag:
        if k<500:
            if ((i.text)==''):  #Checking if the value is null
                up.append('-')
                k+=1
            else:
                up.append(i.text)
                k+=1

    #Locating and Scraping time of post for the comment
    tag = driver.find_elements_by_xpath('//yt-formatted-string[@class="published-time-text above-comment style-scope ytd-comment-renderer"]/a')
    for i in tag:
        if l<500:
            tm.append(i.text)
            l+=1
    
    load = driver.find_element_by_xpath('//div[@class="style-scope ytd-item-section-renderer"][4]')
    p = load.location_once_scrolled_into_view

In [333]:
#Creating DataFrame of the scraped data
df = pd.DataFrame({'Comment':cmt,
                   'Upvote':up,
                   'Time when Posted':tm})

In [334]:
df

                                               Comment Upvote Time when Posted
0    We will work harder to generate better content...    168        1 day ago
1                     all respect goes to technicians.     35        1 day ago
2    everyone associated with this song has created...     90        1 day ago
3    Though I'm late...\nHow much effort ,Behind th...     23     16 hours ago
4    Every steps of this song has own speciality wh...    389       2 days ago
..                                                 ...    ...              ...
495                                                         -       2 days ago
496  How difficult to choreography to allu arjun.no...      -     23 hours ago
497                                   So special Song       3      2 hours ago
498  Omg , then he is the main hero of best dance b...      -        1 day ago
499  Allu Arjun is a great dancer\nHis talents were...      1      6 hours ago

[500 rows x 3 columns]

# 10. Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [2]:
#Calling the webdriver exe file
driver = webdriver.Chrome(r"C:\Users\jjjib\Desktop\Projects\FlipRobo\chromedriver.exe")

In [3]:
driver.get("https://www.hostelworld.com/ ") #Calling the website on the webdriver

In [6]:
#Locating and input into search bar
search = driver.find_element_by_id('search-input-field')
search.send_keys("London")

In [8]:
#Selecting the first option from the drop down list
dd = driver.find_element_by_xpath('//ul[@id="predicted-search-results"]/li[2]')
dd.click()

In [11]:
#Clicking the go button
go = driver.find_element_by_xpath('//button[@id="search-button"]')
go.click()

In [35]:
#Defining empty array to store the scraped data
name = []
dis = []
rat = []
tot = []
ovr = []
pvt = []
dor = []
fac = []
des = []
i=0

In [36]:
for i in range(0,3):
    
    tag1 = driver.find_elements_by_xpath('//h2[@class="title title-6"]/a')  #Locating Hostel name
    for j in tag1:
        name.append(j.text)
    
    tag2 = driver.find_elements_by_xpath('//span[@class="description"]')  #Locating Distance
    for j in tag2:
        dis.append(j.text.split("-")[1])
    
    tag3 = driver.find_elements_by_xpath('//div[@class="rating rating-summary-container big"]/div[1]')  #Locating Rating
    for j in tag3:
        try:
            float(j.text)
            rat.append(j.text)
        except:
            rat.append("-")
    
    tag4 = driver.find_elements_by_xpath('//div[@class="reviews"]')  #Locating Total Reviews
    for j in tag4:
        try:
            tot.append(j.text)
        except:
            tot.append("-")
        
    tag5 = driver.find_elements_by_xpath('//div[@class="keyword"]/span')  #Locating Overall Reviews
    for j in tag5:
        if (i==0): 
            i+=1
        else:
            if (((j.text)=='No Rating') or ((j.text)=='No Rating')):
                ovr.append("-")
            else:
                ovr.append(j.text)
    
    tag6 = driver.find_elements_by_xpath('//div[@class="price-col"][1]')  #Locating Privates from Price
    for j in tag6:
        try:
            pvt.append(j.text.replace('\n',' '))
        except:
            pvt.append("-")
          
    tag7 = driver.find_elements_by_xpath('//div[@class="price-col"][2]')  #Locating Dorms from Price
    for j in tag7:
        try:
            dor.append(j.text.replace('\n',' '))
        except:
            dor.append("-")
    
    tag8 = driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]')  #Locating Facilities
    for j in tag8:
        if (j.text==''):
            fac.append("-")
        else:
            fac.append(j.text.replace('\n',' '))
        
    tag9 = driver.find_elements_by_xpath('//div[@class="rating-factors prop-card-tablet rating-factors small"]')  #Locating Description
    for j in tag9:
        if (j.text==''):
            des.append("-")
        else:
            des.append(j.text.replace('\n',' '))
    
    driver.implicitly_wait(5)
    
    try:
        btn = driver.find_element_by_xpath('//div[@class="pagination-item pagination-next"]') #Clicking on next page option
        btn.click()
    except NoSuchElementException as e:
        pass

In [37]:
print(len(name),len(dis),len(rat),len(tot),len(ovr),len(pvt),len(dor),len(fac),len(des))

78 78 78 78 78 78 78 78 78

In [38]:
df = pd.DataFrame({'Name':name,
                   'Distance':dis,
                   'Rating':rat,
                   'Total Reviews':tot,
                   'Overall Review':ovr,
                   'Privates From':pvt,
                   'Dorms From':dor,
                   'Facilities':fac,
                   'Description':des})

In [39]:
df

,Name,Distance,Rating,Total Reviews,Overall Review,Privates From,Dorms From,Facilities,Description
0,Mornington Camden,4.1km from city centre,8.3,44 Total Reviews,Fabulous,No Privates Available,Dorms From Rs3277,Free WiFi,Perfect Location Superb Staff Fantastic Cleanl...
1,Smart Russell Square Hostel,2.6km from city centre,6.7,9567 Total Reviews,Good,Privates From Rs12769,Dorms From Rs1196,Free WiFi Follows Covid-19 sanitation guidance,Perfect Location Brilliant Staff Awesome Clean...
2,Smart Camden Inn Hostel,4.4km from city centre,8.5,2740 Total Reviews,Fabulous,Privates From Rs4808,Dorms From Rs1718,Free WiFi Follows Covid-19 sanitation guidance,Perfect Location Superb Staff Fantastic Cleanl...
3,Selina Camden,5.5km from city centre,9.2,15 Total Reviews,Superb,Privates From Rs10623,Dorms From Rs4173.85 Rs3548,Free WiFi,Perfect Location Superb Staff Fantastic Cleanl...
4,Queen Elizabeth Chelsea,5.7km from city centre,7.5,3214 Total Reviews,Very Good,Privates From Rs4112,Dorms From Rs1821,Free WiFi,Perfect Location Superb Staff Awesome Cleanliness
...,...,...,...,...,...,...,...,...,...
73,Green Rooms,10.8km from city centre,9.7,76 Total Reviews,Superb,Privates From Rs7844,Dorms From Rs2477,Free WiFi,Perfect Location Superb Staff Fantastic Cleanl...
74,23 Matheson Road,6.2km from city centre,-,6 Total Reviews,-,Privates From Rs5025,No Dorms Available,-,-
75,Park Hotel Essex,24.1km from city centre,8.0,109 Total Reviews,Fabulous,Privates From Rs11636,No Dorms Available,Free Breakfast Follows Covid-19 sanitation gui...,Wonderful Location Marvellous Staff Excellent ...
76,Cranbrook Hotel,14.8km from city centre,-,58 Total Reviews,-,Privates From Rs4148,No Dorms Available,Free Breakfast Follows Covid-19 sanitation gui...,-
77,TLK Apartments & Hotel,19.9km from city centre,-,0 Total Reviews,-,Privates From Rs6745,No Dorms Available,Free WiFi,-